# Build settings
permalink: /blog/:categories/:title/
markdown: kramdown
highlighter: Rouge
plugins: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

incremental: true
live reload: true
host: 0.0.0.0

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Matheus Costa Vieira - Personal Page
description: "Here you can find some personal information, resume and blog from Matheus Costa Vieira"
keywords: "Jekyll, personal information, resume, Matheus, Costa, Vieira, Matheus Costa Vieira, blog"
url: http://matheus-vieira.github.io
baseurl: ""

google_analytics: UA-174941014-1
site.google_analytics_container: GTM-TWNMZ5Q
repo: https://github.com/matheus-vieira/matheus-vieira.github.io
disqus_shortname: "matheuscostavieira"
disqus_site_shortname: "matheuscostavieira"

# Compress
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

# Author settings
author:
  name: mvieira
  full-name: Matheus Costa Vieira
  job: Software Engineer
  bio: "I love God, my wife, my son and my little daughter (an angel) and then I love to create programs!"
  thumb: /images/author.png
  email: matheus.costa.vieira@gmail.com
  url: http://matheus-vieira.github.io
  github: https://github.com/matheus-vieira
  twitter: https://twitter.com/macostavieira
  facebook: https://facebook.com/macovieira
  linkedin: https://linkedin.com/in/macostavieira
  gplus: https://plus.google.com/+MatheusCostaVieira
  instagram: https://instagram.com/matheuscostavieira
  whatsapp: https://api.whatsapp.com/send?phone=5541988024599&text=E ae!
  phone: "5541988024599"
  cellphone: "+55 41 9 88024599"

max_experiences: 4

messages:
  pt-br:
    page-title: Currículo
    print-alert: "Opcionalmente remova o cabeçalho nas opções de impressão"
    print-resume:
      location: "Fazenda Rio Grande - Paraná - Brasil"
      title:
        goal: "Resumo Profissional"
        education: "Formação"
        courses: "Cursos"
        experiences: "Experiências Profissionais"
        institution: "Instituição"
        skills: "Conhecimentos"
        course: "Certificações e Cursos"
        company: "Empresa"
        current: "Atual"
        skills-idiom: "Idiomas"
        skills-languages: "Linguagens"
        skills-cloud: "Provedores de Nuvem"
        skills-framework: "Frameworks"
        skills-others: "Outras"
        backend-development: "Desenvolvimento Backend"
        frontend-development: "Desenvolvimento Frontend"
        cloud-devops: "Nuvem e DevOps"
        databases: "Banco de Dados"
        messaging-caching: "Mensageria e Cache"
        testing-quality: "Teste e Qualidade"
        observability: "Observabilidade"
        version-control: "Controle de Versão"
        professional-goals: "Objetivos Profissionais"
      core-competencies-title: "Competências Essenciais"
      goal: "Engenheiro de Software Sênior com muitos anos de experiência em projeto, desenvolvimento e manutenção de sistemas escaláveis ​​e de alto desempenho. Sólida expertise no ecossistema .NET, soluções em nuvem no Azure, frameworks front-end e melhores práticas de arquitetura de software. Experiência comprovada na liderança de equipes técnicas, criação de bibliotecas reutilizáveis, otimização de pipelines de CI/CD e entrega de soluções centradas no usuário, com testes automatizados e observabilidade em mente."
      backend-development: ".NET 8, .NET Core, Entity Framework Core, C#, Java, VB.NET, Python, COBOL, Delphi"
      frontend-development: "AngularJS, ReactJS, VueJS, KnockoutJS, JavaScript, HTML5, CSS3, Bootstrap"
      cloud-devops: "Azure (Functions, Durable Functions, Event Grid, SQL Databases, Blob Storage, Active Directory, AI Search), CI/CD (GitHub Actions, Azure Pipelines)"
      databases: "SQL Server, Oracle, MongoDB, Elasticsearch"
      messaging-caching: "RabbitMQ, Redis"
      testing-quality: "Unit Testing, Automated Testing, Design Patterns, SOLID Principles, GRASP"
      observability: "Serilog, ELK Stack, Application Insights"
      version-control: "Git, GitLab, TFS, SVN"
      professional-goals: "Projetar soluções inovadoras aplicando princípios de design de software e padrões de arquitetura. Entregar aplicações de alta qualidade apoiadas por testes automatizados e com forte foco na experiência do usuário e na resolução de problemas."
  en-us:
    page-title: Resume
    print-alert: "Optionally remove header in print options"
    print-resume:
      location: "Fazenda Rio Grande - Paraná - Brazil"
      title:
        goal: "Professional Summary"
        education: "Education"
        courses: "Certifications & Courses"
        experiences: "Professional Experiences"
        institution: "Institution"
        skills: "Skills"
        course: "Course"
        company: "Company"
        current: "Actual"
        skills-idiom: "Speak"
        skills-languages: "Languages"
        skills-cloud: "Cloud Providers"
        skills-framework: "Frameworks"
        skills-others: "Others"
        backend-development: "Backend Development"
        frontend-development: "Frontend Development"
        cloud-devops: "Cloud & DevOps"
        databases: "Databases"
        messaging-caching: "Messaging & Caching"
        testing-quality: "Testing & Quality"
        observability: "Observability"
        version-control: "Version Control"
        professional-goals: "Professional Goals"
      core-competencies-title: "Core Competencies"
      goal: "Senior Software Engineer with many years of experience in designing, developing, and maintaining scalable and high-performance systems. Strong expertise in .NET ecosystem, cloud solutions on Azure, front-end frameworks, and software architecture best practices. Proven track record in leading technical teams, creating reusable libraries, optimizing CI/CD pipelines, and delivering user-centric solutions with automated testing and observability in mind."
      backend-development: ".NET 8, .NET Core, Entity Framework Core, C#, Java, VB.NET, Python, COBOL, Delphi"
      frontend-development: "AngularJS, ReactJS, VueJS, KnockoutJS, JavaScript, HTML5, CSS3, Bootstrap"
      cloud-devops: "Azure (Functions, Durable Functions, Event Grid, SQL Databases, Blob Storage, Active Directory, AI Search), CI/CD (GitHub Actions, Azure Pipelines)"
      databases: "SQL Server, Oracle, MongoDB, Elasticsearch"
      messaging-caching: "RabbitMQ, Redis"
      testing-quality: "Unit Testing, Automated Testing, Design Patterns, SOLID Principles, GRASP"
      observability: "Serilog, ELK Stack, Application Insights"
      version-control: "Git, GitLab, TFS, SVN"
      professional-goals: "To design innovative solutions by applying software design principles and architecture patterns. To deliver high-quality applications backed by automated testing and a strong focus on user experience and problem-solving."

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog
  - slug: contact
    title: Contact
  - slug: courses
    title: Courses
  - slug: resume
    title: Resume
  - slug: study
    title: Study

collections:
  - graduations
  - experiences
  - skills

exclude:
  [
    "config.rb",
    "src",
    "Gemfile",
    "Gemfile.lock",
    "package.json",
    "README.md",
    "Rakefile",
  ]
